mate-desktop/eom

- src/eom-image.c
- src/eom-jobs.c
adapted from:
https://git.gnome.org/browse/eog/commit/?id=4626596c2c179bfe35c4212efced15c38d7337d6
> don't change file permissions when saving the modified image

- src/eom-thumb-nav.c
- src/eom-thumb-view.c
> GTK3: fix broken thumbview

- data/eom-image-properties-dialog.ui
- data/eom-preferences-dialog.ui
- data/org.mate.eom.gschema.xml.in
- src/eom-close-confirmation-dialog.c
- src/eom-file-chooser.c
- src/eom-image.c
- src/eom-image.h
- src/eom-preferences-dialog.c
- src/eom-print-preview.c
- src/eom-print.c
- src/eom-scroll-view.c
- src/eom-scroll-view.h
> fixing deprecations and back ports

- data/eom-multiple-save-as-dialog.ui
- src/eom-error-message-area.c
- src/eom-image.c
- src/eom-properties-dialog.c
- src/eom-scroll-view.c
- src/eom-thumb-nav.c
- src/eom-thumb-view.c
Please test.
Note, the gtk_menu_popup commits should help for wayland, but for a test under wayland you need to revert https://github.com/mate-desktop/eom/commit/52e24934ab37f874df2511ed760b2e39b49b5048,
and pray that other adjustments are not needed.
> deprecations and warnings

- src/eom-util.c
> don't use deprecated gtk_show_uri

- cut-n-paste/toolbar-editor/egg-editable-toolbar.c
- cut-n-paste/toolbar-editor/egg-toolbar-editor.c
- src/eom-close-confirmation-dialog.c
- src/eom-file-chooser.c
- src/eom-window.c
The expected with this PR: the same icons like before
> avoid deprecated GtkStock

- src/eom-save-as-dialog-helper.c
- src/eom-scroll-view.c
- src/eom-thumb-view.c
> Warnings deprecations

- data/eom-toolbar.xml
- data/eom-ui.xml
- src/eom-properties-dialog.c
- src/eom-scroll-view.c
- src/eom-thumb-view.c
- src/eom-util.c
- src/eom-util.h
- src/eom-window.c
> open image in filebrowser and improvement for properties-dialog

- src/Makefile.am
- src/eom-exif-util.c
- src/eom-exif-util.h
- src/eom-metadata-sidebar.c
- src/eom-metadata-sidebar.h
- src/eom-properties-dialog.c
- src/eom-sidebar.c
- src/eom-window.c
- src/eom-window.h
This is the second part for enable the sidebar.
The first commits are already submitted in other PR.
https://github.com/mate-desktop/eom/pull/171
Please test.
> Sidebar and more

- plugins/fullscreen/eom-fullscreen-plugin.c
- plugins/fullscreen/eom-fullscreen-plugin.h
- plugins/reload/eom-reload-plugin.c
- plugins/reload/eom-reload-plugin.h
- plugins/statusbar-date/eom-statusbar-date-plugin.c
- plugins/statusbar-date/eom-statusbar-date-plugin.h
- src/Makefile.am
- src/eom-list-store.c
- src/eom-window-activatable.c
- src/eom-window-activatable.h
- src/eom-window.c
Those are local leftovers from trying to fix the warnings with closing eom.
I don't think it will hurt to back port them.
Please test.
> some more backports

- src/eom-scroll-view.c
fix for https://github.com/mate-desktop/eom/issues/96
Please test.
> fix no resampling on zoom

- data/eom-image-properties-dialog.ui
- src/eom-metadata-sidebar.c
- src/eom-properties-dialog.c
UI changes are from myself.
Please test.
> Make the URI-label in the properties dialog a button showing the folder

- src/eom-image-private.h
- src/eom-image.c
Please test.
First commit closed a leak.
The other ones are bugfixes and belongs to libexif support.
> some fixes

- src/eom-close-confirmation-dialog.c
- src/eom-close-confirmation-dialog.h
- src/eom-metadata-sidebar.c
- src/eom-scroll-view.c
- src/eom-util.c
- src/eom-util.h
- src/eom-window.c
> Deprecations

- configure.ac
- data/Makefile.am
- src/Makefile.am
- src/eom-window.c
- src/eom.gresource.xml
- src/main.c
I will migrate more files later.
At the moment i need this to backport some visual improvements for the sidebar.
Please test.
> Initial GResource migration

- data/metadata-sidebar.ui
- src/eom-metadata-sidebar.c
- src/eom-metadata-sidebar.h
- src/eom-properties-dialog.c
- src/eom-sidebar.c
- src/eom-window.c
> Sidebar finishing

- src/eom-list-store.c
Apply https://gitlab.gnome.org/GNOME/eog/commit/8032c8a0c6700966afbe77632c03a00ae9a878d0
> fix a memory leak

- .travis.yml
Add lost the 'build_scripts' section to see the building output.
> [ci] add build scripts

- jpegutils/transupp-6b.c
- jpegutils/transupp-6b.h
- jpegutils/transupp-8a.c
- src/eom-application-internal.h
Update [FSF address](https://www.fsf.org/about/contact/)
> Update FSF address

- jpegutils/transupp-6b.c
- jpegutils/transupp-6b.h
- src/eom-application-activatable.c
- src/eom-application-activatable.h
- src/eom-application.c
- src/eom-close-confirmation-dialog.c
- src/eom-close-confirmation-dialog.h
- src/eom-image.c
- src/eom-metadata-sidebar.c
- src/eom-preferences-dialog.c
- src/eom-properties-dialog.c
- src/eom-scroll-view.c
- src/eom-transform.c
- src/eom-window-activatable.c
- src/eom-window-activatable.h
- src/eom-window.c
- src/main.c
`find . -regextype posix-extended -regex '.*\.(c|h|ac)' -exec sed --in-place 's/[[:space:]]\+$//' {} \+`
like rbuj do on [https://github.com/mate-desktop/mate-control-center/pull/463](https://github.com/mate-desktop/mate-control-center/pull/463).
> Remove trailing whitespaces

- data/eom.appdata.xml.in
- plugins/Makefile.am
Improve the previous PR.
https://github.com/mate-desktop/eom/pull/245#issuecomment-553394968
> fix makefile rules

- src/eom-print-preview.c
The preview is at third tab from print-dialog.
Please review.
> EomPrintPreview: Fix preview thumbnail on HiDPI displays

- src/eom-window.c
> eom-window: expand the comment on about dialog

- src/eom-preferences-dialog.c
- src/eom-properties-dialog.c
- src/eom-util.c
- src/eom-util.h
Based on https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188
> handle GDK_SCROLL_SMOOTH when handling mouse scroll on tabs

- help/C/index.docbook
- reported by translators at transifex
> user-guide: fix wrong informations
