src/eom-image.c
adapted from:
https://git.gnome.org/browse/eog/commit/?id=4626596c2c179bfe35c4212efced15c38d7337d6
=> [1.8] don't change file permissions when saving the modified image

configure.ac
to prevent possible "undefined reference to `forkpty'" and "undefined reference to `openpty'" linker errors
=> Add libutil to PYTHON_LIBS

src/eom-thumb-view.c, src/eom-window.c
to avoid:
(eom:22247): EOM-CRITICAL **: eom_list_store_length: assertion 'EOM_IS_LIST_STORE (store)' failed
(eom:14608): GLib-GObject-WARNING **: The property GtkCellRendererPixbuf:follow-state is deprecated and shouldn't be used anymore. It will be removed in a future version.
=> fix a eom-critical + deprecated follow-state property

cut-n-paste/toolbar-editor/egg-editable-toolbar.c
action_sensitive_cb can be called with the dnd tool item
when it doesn't have an ancestor.
taken from:
https://git.gnome.org/browse/eog/commit/?id=c754959
=> GTK3: toolbar-editor: Fix a crash when dropping an item to the toolbar

src/eom-scroll-view.c
make tall images scroll bad after zoom-ins until hbar appears
Just try to zoom in some tall but narrow image (when vbar is visible but no hbar yet). The vbar will be freezed until hbar appears: this makes impossible to see all the image moving it by the vbar or the mouse.
=> mispositioned brackets in update_scrollbar_values

src/eom-scroll-view.c
fixes https://github.com/mate-desktop/eom/issues/117
@raveit65 @lukefromdc @XRevan86 
Please test it in GTK+2 build as well if you can. I thought it might break it there, but it seems to work for me with some svg icons I've tried.
=> fix svg rendering that's broken with GTK+3

src/eom-scroll-view.c
Adapted from https://git.gnome.org/browse/eog/commit/id=3d1859e321b9dea27e49bab9626044f3f5835420
I've tested using https://www.nasa.gov/sites/default/files/thumbnails/image/crop_p_color2_enhanced_release.png and eom no longer crashes and zoom and scroll performance is restored.
=> Fix the zoom and scroll performance. Closes #105.

src/eom-error-message-area.c
https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-6855
https://bugzilla.gnome.org/show_bug.cgi?id=770143
=> eom: Out-of-bounds write when passing invalid UTF-8 to GMarkup

src/eom-window.c
avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_window
=> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

src/eom-plugin-engine.c
For distros which switched to python3.
I think this is high theoretical, as i don't see that eom-plugins are shipped anywhere.
But this fixes runtime requires to libpeas-loader-python3.
=> plugins: Use Python 3.x for Python plugins

data/eom-ui.xml, src/eom-window.c
Should be working with both keyboard and mouse.
=> toolbar: add missing popup menu for launching toolbar editor

data/Makefile.am, data/eom-image-properties-dialog.ui, src/eom-metadata-sidebar.c, src/eom-properties-dialog.c, src/eom-properties-dialog.h, src/eom-window.c, src/eom-window.h, src/eom.gresource.xml
`EomPropertiesDialog: Convert to GtkBuilder template` fixes
- known runtime warning `GtkDialog mapped without a transient parent. This is discouraged.`
- makes it possible to fix deprecated `gtk_show_uri`
Please test.
=> some fixes for properties dialog

src/eom-image.c, src/eom-image.h, src/eom-list-store.c
This is based on the [GNOME bug](https://bugzilla.gnome.org/show_bug.cgi?id=764139) referenced on #130.
I've backported the patches to EOM, but I personally don't notice any difference when opening a folder with over 10k images: with and without the patch, it takes eom about ~1.6s to load entirely, and `g_file_query_info` got called at most 2 times, so no difference.
Maybe someone with more (or larger) files can notice a difference?
=> Performance improvement on open

help/C/index.docbook
There is no File menu item in toolbar, it's Image, and edit
actions can be found under Edit menu item instead of Image menu
item.
Fix Open Image dialog title.
TODO: update "Setting your Page Settings" section
=> Help - fix gui labels

src/eom-window.c
When changing page settings on the print dialog, the new settings should persist across sessions of eom.
To test this:
1. Open the Print dialog
2. Select a different Page Size (US Letter, A4, etc.)
3. Print the file (into a PDF is fine too, no need to waste paper :wink:)
4. Close eom
5. Go back to step 1 and see which Page Size is selected by default
Without this patch, the last-used Page Size is not remembered. With this patch, the last-used Page Size should be automatically selected.
Fixes #206
=> Use persistent page setup

help/C/index.docbook, help/C/legal.xml, help/eom.pot
To upgrade the manual:
sudo dnf install -y docbook5-schemas
xsltproc --output index-new.docbook /usr/share/xml/docbook5/stylesheet/upgrade/db4-upgrade.xsl index.docbook
xsltproc --output legal-new.xml /usr/share/xml/docbook5/stylesheet/upgrade/db4-upgrade.xsl legal.xml
To validate the manual:
xmllint --noout --relaxng /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng help/C/index.docbook
jing /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng help/C/index.docbook
yelp-check validate help/C/index.docbook
To view the manual:
yelp file:///full_path/index.docbook
Note: docbook5-schemas should be installed in your system in order to view the manual (DEPENDENCY)
=> Upgrade the manual to docbook 5.0

data/eom.desktop.in.in, src/eom-list-store.c
This allows eom to navigate through all image files in a directory without having to manually load them into the store.
Fixes #218
=> store: Add any image file in the current directory to the store

src/eom-window.c
This should fix two memory leaks related to the "Open with" menu.
7bfca3a: The GAppInfos created by g_app_info_get_all_for_type() in eom_window_update_openwith_menu() aren't freed
2efa136: connect_proxy_cb() can be called repeatedly for the same menu items, resulting in lots of redundant GClosures hanging around
This should help with #139, but it won't completely fix it.
=> Open with menu leaks

data/eom.desktop.in.in
I restored the image list from [Eye of GNOME](https://gitlab.gnome.org/GNOME/eog/blob/master/data/eog.desktop.in.in) and added the `image/*` wildcard at the end.
Partially fixes https://github.com/mate-desktop/mate-control-center/issues/443
=> Restore image types list and add wildcard

src/eom-image.c, src/eom-metadata-reader-png.c, src/eom-window.c
This is a backport of eog's icc color profile fixes. Test by comparing eog versus eom with the image posted on https://github.com/mate-desktop/eom/issues/170#issuecomment-507069675 (the one in the dropbox link)
Fixes #170
=> Fix color profiles

.travis.yml, cut-n-paste/toolbar-editor/egg-editable-toolbar.c, cut-n-paste/toolbar-editor/egg-toolbar-editor.c, plugins/reload/eom-reload-plugin.c, src/eom-properties-dialog.c, src/eom-window.c
Suppress GtkAction warnings which can't be fixed without removing icons from menus.
So, no need to let them spam our build logs, in result you overlook really important warnings.
Show those warnings in debian build only, to make one team member happy.
=> Suppress GtkAction deprecation warnings

src/eom-window.c
eom-window.c:3153:20: warning: variable ‘priv’ set but not used [-Wunused-but-set-variable]
=> remove warning: variable ‘priv’ set but not used

cut-n-paste/toolbar-editor/egg-toolbars-model.h, src/eom-thumb-view.c
```
egg-toolbars-model.h:113:10: warning: redundant redeclaration of ‘egg_tb_model_flags_get_type’ [-Wredundant-decls]
eggtypebuiltins.h:13:23: warning: redundant redeclaration of ‘egg_tb_model_flags_get_type’ [-Wredundant-decls]
eom-thumb-view.c:91:40: warning: redundant redeclaration of ‘eom_thumb_view_init’ [-Wredundant-decls]
```
=> remove warnings: redundant redeclaration [-Wredundant-decls]

src/eom-transform.c
```
eom-transform.c:135:15: warning: using integer absolute value function ‘abs’ when argument is of floating point type ‘gdouble’ {aka ‘double’} [-Wabsolute-value]
eom-transform.c:136:16: warning: using integer absolute value function ‘abs’ when argument is of floating point type ‘gdouble’ {aka ‘double’} [-Wabsolute-value]
```
=> remove warnings: incorrect usage of abs() [-Wabsolute-value]

eom.pot, src/eom-window.c
This should fix problems with `msgstr[0]` mentioned at https://github.com/mate-desktop/eom/pull/245.
Note that our other projects have similar code, e.g. in right-click menu in Caja:
```C
if (selection_count == 0 || selection_count == 1) {
label_with_underscore = g_strdup (_("Open in New _Window"));
} else {
label_with_underscore = g_strdup_printf (ngettext("Open in %'d New _Window",
"Open in %'d New _Windows",
selection_count),
selection_count);
}
```
Translation for one window:
```po
#. add the "open in new window" menu item
#: ../src/file-manager/fm-directory-view.c:8579
#: ../src/file-manager/fm-directory-view.c:8896
#: ../src/file-manager/fm-tree-view.c:1284 ../src/caja-places-sidebar.c:2692
msgid "Open in New _Window"
msgstr "Открыть в _новом окне"
```
Translation for multiple …
=> add missing format specifier for ngettext

src/eom-application.c, src/eom-image-private.h, src/eom-image.c, src/eom-metadata-reader-jpg.c, src/eom-metadata-reader-png.c, src/eom-metadata-reader.c, src/eom-window.c, src/main.c
EDIT:
~~Please test with: `./configure --without-cms --without-x ...`~~
After the last commit bb428f6, it support both X and wayland, no special configuration parameters required.
=> enable wayland support

src/Makefile.am
Preprocessing warning for file: src/eom-print.c
```
eom-print.c:22:20: Cannot find include file config.h on search path:
/home/robert/eom/src;.;../jpegutils;../cut-n-paste/toolbar-editor;/usr/inclu
de/gtk-3.0;/usr/include/pango-1.0;/usr/include/glib-2.0;/usr/lib64/glib-2.0/
include;/usr/include/harfbuzz;/usr/include/fribidi;/usr/include/freetype2;/u
sr/include/libpng16;/usr/include/cairo;/usr/include/pixman-1;/usr/include/gd
k-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/gio-unix-
2.0;/usr/include/atk-1.0;/usr/include/at-spi2-atk/2.0;/usr/include/at-spi-2.
0;/usr/include/dbus-1.0;/usr/lib64/dbus-1.0/include;/usr/include/mate-deskto
p-2.0;/usr/include/startup-notification-1.0;/usr/include/dconf;/usr/include/
gtk-3.0/unix-print;/usr/include/libpeas-1.0;/usr/include/gobjec …
```
=> Remove preprocessing warnings

.travis.yml, Makefile.am, configure.ac, thumbnailer/Makefile.am, thumbnailer/eom-thumbnailer.c, thumbnailer/eom-thumbnailer.thumbnailer.in
```shell
$ exiftool ~/.cache/thumbnails/normal/*.png
<cut>
======== /home/robert/.cache/thumbnails/normal/fe4fb554664b67fc6c8e33157fa9c88e.png
ExifTool Version Number         : 11.70
File Name                       : fe4fb554664b67fc6c8e33157fa9c88e.png
Directory                       : /home/robert/.cache/thumbnails/normal
File Size                       : 20 kB
File Modification Date/Time     : 2020:01:21 18:49:11+01:00
File Access Date/Time           : 2020:01:21 18:49:11+01:00
File Inode Change Date/Time     : 2020:01:21 18:49:11+01:00
File Permissions                : rw-------
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 128
Image Height                    : 86
Bit Depth …
```
=> Add eom-thumbnailer for webp files

.build.yml
seems we need to build with mate-desktop 1.22 here
this PR fixes the build in arch and debian:
```
eom-thumbnail.c: In function 'create_thumbnail_from_pixbuf':
eom-thumbnail.c:126:10: warning: implicit declaration of function 'mate_desktop_thumbnail_scale_down_pixbuf'; did you mean 'mate_desktop_thumbnail_path_for_uri'? [-Wimplicit-function-declaration]
126 |  thumb = mate_desktop_thumbnail_scale_down_pixbuf (pixbuf,
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|          mate_desktop_thumbnail_path_for_uri
```
=> [1.22] Travis CI: build mate-desktop from 1.22 branch

help/C/index.docbook
Reported by translators. It's Ctrl+ F9 and not F9.
Test:
```shell
$ yelp help:eom/eom-whenyoustart
```
```
$ yelp help:eom/eom-open-folder
```
Closes #262
=> help: Fix Image Collection shortcut

help/C/index.docbook
- It avoids confusing the user by using only one term for the sidepane, and it also fixes its keyboard shortcut.
- Ctrl+W terminates the application.
Test:
```
$ yelp help:eom/eom-whenyoustart
$ yelp help:eom/eom-fullscreen
```
=> help: Fix some incongruencies

data/Makefile.am
test:
```shell
$ diff data/eom.desktop.master data/eom.desktop
175,186d174
< Icon[ca]=eom
< Icon[cs]=eom
< Icon[da]=eom
< Icon[es]=eom
< Icon[gl]=eom
< Icon[it]=eom
< Icon[lt]=eom
< Icon[ms]=eom
< Icon[nb]=eom
< Icon[nl]=eom
< Icon[uk]=eom
< Icon[zh_TW]=eom
```
=> eom.desktop: Do not collect the translation for Icon

cut-n-paste/toolbar-editor/egg-editable-toolbar.c, src/eom-image.c, src/eom-jobs.c, src/eom-thumb-view.c, src/eom-uri-converter.c, src/eom-window.c
Removed warnings (16):
```
egg-editable-toolbar.c:1315:29: warning: cast between incompatible function types from ‘void (*)(GtkWidget *)’ {aka ‘void (*)(struct _GtkWidget *)’} to ‘void (*)(void *, void *)’ [-Wcast-function-type]
1315 |   g_list_foreach (children, (GFunc) gtk_widget_destroy, NULL);
|                             ^
--
egg-editable-toolbar.c:1385:33: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
1385 |       g_list_foreach (children, (GFunc) g_free, NULL);
|                                 ^
--
eom-window.c:1602:25: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
1602 |  g_slist_foreach (list, (GFunc) g_free, NULL);
| …
```
=> Remove warnings: cast between incompatible function types

.build.yml
I think for stable branches it is sufficient to use default compiler warnings level from eom.
PRs target mostly only master.
=> Travis CI: set compiler warning level to maximum

.build.yml
=> Travis CI: build: drop dbus-glib

cut-n-paste/toolbar-editor/egg-editable-toolbar.c
```
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/[[:space:]]*$//' {} \;
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/\t*$//' {} \;
```
=> egg-editable-toolbar: Remove trailing spaces/tabs

src/eom-scroll-view.c
```
eom-scroll-view.c:657:27: warning: passing argument 1 of 'gtk_widget_queue_resize' from incompatible pointer type [-Wincompatible-pointer-types]
657 |  gtk_widget_queue_resize (view);
|                           ^~~~
```
=> eom-scroll-view: Remove warning incompatible-pointer-types

src/eom-image.c
```
eom-image.c:961:1: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
961 | #if LIBRSVG_CHECK_FEATURE(SVGZ)
| ^~~~~~~~~~~~~~~~~
```
=> eom-image: warning -Wexpansion-to-defined

src/eom-uri-converter.c
test
```
$ CFLAGS="-g -O0 -fanalyzer" LDFLAGS="-fanalyzer" ./autogen.sh --enable-debug && make &> make.log
$ diff make-master.log make.log
```
```
< eom-uri-converter.c: In function 'eom_uri_converter_do':
< eom-uri-converter.c:797:14: warning: dereference of NULL 'repl_str' [CWE-690] [-Wanalyzer-null-dereference]
<   797 |  if (repl_str->len > 0) {
<       |      ~~~~~~~~^~~~~
<   'eom_uri_converter_do': event 1
<     |
<     |  721 | eom_uri_converter_do (EomURIConverter *conv, EomImage *image,
<     |      | ^~~~~~~~~~~~~~~~~~~~
<     |      | |
<     |      | (1) entry to 'eom_uri_converter_do'
<     |
<   'eom_uri_converter_do': event 2
<     |
<     |eom-uri-converter.h:10:42:
<     |   10 | #define EOM_TYPE_URI_CONVERTER          (eom_uri_converter_get_type ())
< …
```
=> eom-uri-converter: dereference of NULL 'repl_str' reported by gcc

cut-n-paste/toolbar-editor/egg-editable-toolbar.c, src/eom-image.c, src/eom-list-store.c, src/eom-window.c
```
egg-editable-toolbar.c:471:30: warning: declaration of 'screen' shadows a previous local [-Wshadow]
471 |                   GdkScreen *screen;
|                              ^~~~~~
--
egg-editable-toolbar.c:897:22: warning: declaration of 'action' shadows a previous local [-Wshadow]
897 |           GtkAction *action;
|                      ^~~~~~
--
eom-window.c:3235:14: warning: declaration of 'action' shadows a parameter [-Wshadow]
3235 |   GtkAction *action;
|              ^~~~~~
--
eom-image.c:2249:9: warning: declaration of 'supported_mime_types' shadows a global declaration [-Wshadow]
2249 |  GList *supported_mime_types, *result;
|         ^~~~~~~~~~~~~~~~~~~~
--
eom-list-store.c:410:14: warning: declaration of 'image' shadows a previous local [-Wshadow]
410 |    EomImage …
```
=> Remove warning -Wshadow

cut-n-paste/toolbar-editor/egg-editable-toolbar.c, src/eom-file-chooser.c, src/eom-image.c
```
cut-n-paste/toolbar-editor/egg-editable-toolbar.c:1116:15: style: Condition 'toolbar' is always true [knownConditionTrueFalse]
if (dock && toolbar && gtk_widget_get_parent (toolbar) == NULL)
^
cut-n-paste/toolbar-editor/egg-editable-toolbar.c:1111:7: note: Assuming that condition '!etoolbar->priv->fixed_toolbar' is not redundant
if (!etoolbar->priv->fixed_toolbar) return;
^
cut-n-paste/toolbar-editor/egg-editable-toolbar.c:1113:27: note: Assignment 'toolbar=etoolbar->priv->fixed_toolbar', assigned value is 0
toolbar = etoolbar->priv->fixed_toolbar;
^
cut-n-paste/toolbar-editor/egg-editable-toolbar.c:1116:15: note: Condition 'toolbar' is always true
if (dock && toolbar && gtk_widget_get_parent (toolbar) == NULL)
^
```
```
src/eom-file-chooser.c:382:15: style: Condition 'pixbuf!=NULL' …
```
=> Remove cppcheck warning knownConditionTrueFalse

data/eom.desktop.in.in
```
$ desktop-file-validate data/eom.desktop 
data/eom.desktop: hint: value item "RasterGraphics" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Graphics;2DGraphics
```
=> Fix desktop file validation warning

configure.ac, data/Makefile.am, data/eom.appdata.xml.in.in, plugins/Makefile.am, plugins/fullscreen/fullscreen.plugin.desktop.in.in, plugins/reload/reload.plugin.desktop.in.in, plugins/statusbar-date/statusbar-date.plugin.desktop.in.in, po/POTFILES.in, src/eom-window.c
Test:
```
$ grep homepage data/eom.appdata.xml
<url type="homepage">https://mate-desktop.org</url>
$ find . -name *.plugin -exec grep -H Website {} \;
./plugins/fullscreen/fullscreen.plugin:Website=https://mate-desktop.org
./plugins/reload/reload.plugin:Website=https://mate-desktop.org
./plugins/statusbar-date/statusbar-date.plugin:Website=https://mate-desktop.org
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
```
- Change the url prefix from `http` to `https` of the screenshot in the eom.appdata.xml file, which is used in applications such as `gnome-software` (eom.appdata.xml.in.in)
- Set all [AC_INIT](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Initializing-configure.html) fields including optional ones (configure.ac):
```
Macro: …
```
=> build: Use PACKAGE_URL variable

Makefile.am, configure.ac, data/Makefile.am, help/Makefile.am, plugins/Makefile.am, plugins/reload/eom-reload-plugin.c, src/eom-save-as-dialog-helper.c, src/eom-window.c, src/main.c
```
$ find /usr/share/locale -type f -name 'eom.mo' -exec sudo rm -f {} +
$ find /usr/share/help -type d -name 'eom' -exec sudo rm -fr {} +
$ ./autogen.sh --prefix=/usr && make && sudo make install
$ find /usr/share/locale -type f -name 'eom.mo' -exec du -ch {} + | grep total
2,7M	total
$ find /usr/share/help -type d -name 'eom' -exec du -ch {} + | grep total
6,4M	total
```
```
$ find /usr/share/locale -type f -name 'eom.mo' -exec sudo rm -f {} +
$ find /usr/share/help -type d -name 'eom' -exec sudo rm -fr {} +
$ ./autogen.sh --prefix=/usr --disable-nls && make && sudo make install
$ find /usr/share/locale -type f -name 'eom.mo' -exec du -ch {} + | grep total
$ find /usr/share/help -type d -name 'eom' -exec du -ch {} + | grep total
124K	total
```
=> build: allow users to disable gettext support (--disable-nls)

src/eom-window.c
```
eom-window.c:3759:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
eom-window.c:3760:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
eom-window.c:3761:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
eom-window.c:3762:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
eom-window.c:3763:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} …
```
=> eom-window: Remove -Wmissing-field-initializers warnings

data/eom-image-properties-dialog.ui, data/eom-preferences-dialog.ui
Unfortunately, there’s a [GTK bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/4339) that prevents the status bar from  
being fully accessible, but at least this will make the Info and Preferences  
dialogs a bit easier to navigate.
=> Accessibility: add proper mnemonic relations and labelling

src/eom-window.c
```
eom-window.c:4346:31: warning: incompatible pointer types passing 'GList **' (aka 'struct _GList **') to parameter of type 'GList *' (aka 'struct _GList *'); remove & [-Wincompatible-pointer-types]
g_app_info_launch (app_info, &files,
^~~~~~
/usr/include/glib-2.0/gio/gappinfo.h:175:76: note: passing argument to parameter 'files' here
GList                *files,
^
```
Test:
- set default editor
```
gsettings set org.mate.eom.ui external-editor /usr/share/applications/gimp.desktop
```
- add "Edit Image" toobar button if not present: right clic on toolbar, click on Toolbar menu item, drag & drop "Edit Image".
- click on "Edit Image" toobar button
=> eom-window: fix warning incompatible-pointer-types

README
It looks like the wiki's URL format has changed. Just a small change to point to the modern format.
=> Updated url in readme to point to working link

src/eom-close-confirmation-dialog.c, src/eom-scroll-view.c
```
eom-scroll-view.c:1305:31: warning: cast from function call of type 'int' to non-matching type 'double' [-Wbad-function-cast]
image_offset_x = (double) gdk_pixbuf_get_width (priv->pixbuf);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eom-scroll-view.c:1309:31: warning: cast from function call of type 'int' to non-matching type 'double' [-Wbad-function-cast]
image_offset_y = (double) gdk_pixbuf_get_height (priv->pixbuf);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eom-scroll-view.c:1314:31: warning: cast from function call of type 'int' to non-matching type 'double' [-Wbad-function-cast]
image_offset_x = (double) gdk_pixbuf_get_width (priv->pixbuf);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eom-scroll-view.c:1315:31: warning: cast from function call of type 'int' to non-matching type 'double' …
```
=> Fix some build warnings about bad function cast

src/eom-window.c
Fix the cppcheck warning:
```
cppcheck --enable=all --quiet .
```
```
src/eom-window.c:4702:9: style: Variable 'screen' is assigned a value that is never used. [unreadVariable]
screen = gtk_widget_get_screen (GTK_WIDGET (window));
^
```
```
src/eom-window.c:577:33: style: Variable 'show_image_collection' is assigned a value that is never used. [unreadVariable]
gboolean show_image_collection = FALSE;
^
```
=> eom-window: variable is assigned a value that is never used

src/eom-scroll-view.c
```
eom-scroll-view.c:1035:8: warning: explicitly assigning value of variable of type 'int' to itself [-Wself-assign]
yofs = yofs;
~~~~ ^ ~~~~
eom-scroll-view.c:1040:8: warning: explicitly assigning value of variable of type 'int' to itself [-Wself-assign]
xofs = xofs;
~~~~ ^ ~~~~
```
=> explicitly assigning value of variable of type 'int' to itself

configure.ac
Check for ImageMagick 7 first, then for ImageMagick 6. Original (the reversed) ordering might lead accidentially to `HAVE_IMAGEMAGICK6` with ImageMagick 7.
Build failure at Fedora 38 (with ImageMagick 7): https://koji.fedoraproject.org/koji/buildinfo?buildID=2107065
Successful builds with this pull request applied at:
- Fedora 38 (with ImageMagick 7): https://koji.fedoraproject.org/koji/taskinfo?taskID=95943021
- Rocky Linux (with ImageMagick 6): https://koji.fedoraproject.org/koji/taskinfo?taskID=95943024
Pull request results from https://bugzilla.redhat.com/show_bug.cgi?id=2159313 since ImageMagick 7 landed in Fedora Rawhide.
=> Fix building with ImageMagick 7

cut-n-paste/toolbar-editor/egg-toolbars-model.c
Added include <libxml/xmlsave.h> to allow build with libxml 2.12.0.
This PR fixes buid issue with libxml 2.12.0
```console
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/eom-1.27.1/cut-n-paste/toolbar-editor'
CC       libtoolbareditor_la-egg-toolbars-model.lo
egg-toolbars-model.c: In function 'egg_toolbars_model_to_xml':
egg-toolbars-model.c:78:3: error: 'xmlIndentTreeOutput' undeclared (first use in this function)
78 |   xmlIndentTreeOutput = TRUE;
|   ^~~~~~~~~~~~~~~~~~~
egg-toolbars-model.c:78:3: note: each undeclared identifier is reported only once for each function it appears in
egg-toolbars-model.c: In function 'egg_toolbars_model_load_toolbars':
egg-toolbars-model.c:591:9: warning: implicit declaration of function 'xmlParseFile'; did you mean 'xmlSaveFile'? …
```
=> fix building with new libxml 2.12.0

src/eom-window.c
To reproduce:
* obtain/create an image file, foo.png
* obtain/create unsupported (gdk pixbuf) file, foo.txt
* run `eom foo.png foo.txt`
* displays foo.png, showing 1/2 in bottom right statusbar:
* navigate to 2nd file which is an invalid (image) file
* `eom` displays _"Could not load image 'foo.txt'"_ 
* status bar continues to incorrectly show "1/2", referencing the previous file
Post fix:
* as above, navigate to 2nd file which is invalid:
=> eom-window: update image counter even if current thumbnail is for failed image

src/eom-window.c
Same as Eye of GNOME's https://gitlab.gnome.org/GNOME/eog/-/commit/b23508382f0131d9961e437fe8c8453adeb84faa. The button codes for the backwards and forwards buttons on mice apparently changed at some point, long ago...
=> eom-window: support newer mouse forward/back button codes
